build/Base.dockerfile, build/configs/ghostery.mozconfig, ci.multibranch.Jenkinsfile, ci/build-helpers.groovy
=> Mar signing

ci/submitter.py
This corresponds to the platform sent in the update request to balrog.
=> Update Windows platform mapping for balrog

branding/ghostery/configure.sh
Customizing the values in https://searchfox.org/mozilla-central/source/build/application.ini.in
=> More Ghostery branding

ci.nightly.Jenkinsfile, ci/submitter.py
* Only trigger nightly builds if there is not already a tag on the master branch tip.
* Update URLs for the github org change.
=> Nightly improvements

patches/.index, patches/0005-Change-new-tab-page-and-home-page-url.patch
=> Change new tab page and home page url

branding/ghostery/pref/firefox-branding.js
=> Enable UA compat mode

patches/.index, patches/0008-Remove-tracking-protection-panel-from-url-bar.patch, patches/0009-Hide-Protection-Dashboard-link-from-right-burger-men.patch
Ref #52 
Removes the tracking protection panel from the left-side of the url bar.
=> Remove tracking protection panel.

branding/ghostery/pref/firefox-branding.js
Fix parse error in firefox-branding.js.
=> Fix missing semi-colon in prefs

brands/ghostery/branding/pref/firefox-branding.js
=> Disable System Addon updates

brands/ghostery/branding/pref/firefox-branding.js
#196 Disable addon recommendations. Done via pref.
=> Disable addon recommendations.

brands/ghostery/branding/pref/firefox-branding.js, patches/.index, patches/0012-Hide-Recommend-as-you-browser-preferences.patch
=> Disable addon/feature recommendations while browsing. Fixes #208.

brands/ghostery/branding/pref/firefox-branding.js, patches/.index, patches/0017-Update-uninstaller-survey-URL.patch
* Support urls (see #241) go via `get.ghosterybrowser.com/support/` 
* Settings service (see #198) via `get.ghosterybrowser.com/settings/`
* Uninstaller survey link #242
=> Update product urls

brands/ghostery/branding/branding.nsi, patches/.index, patches/0018-Update-strings-for-windows-module-manifest.patch, patches/0019-Fix-installer-trademark-info.patch
Ensures that on windows the metadata of all executables (browser, updater, installer) is correctly branded.
=> Update windows manifest copyright and trademark strings.

brands/ghostery/branding/pref/firefox-branding.js, patches/.index, patches/0023-Hide-Library-Synced-Tabs-from-the-menu-panel.patch, patches/0024-Hide-Firefox-Home-Content-from-preferences.patch, patches/0025-Rename-Firefox-Home-to-Brand-Home.patch
* Extension abuse reporting. #186
* Synced tabs in library. #223
* Activity stream. #131 
* Corraborator. #141 
* Firefox Home Content. #60
=> Disabling features

patches/0005-Change-new-tab-page-and-home-page-url.patch, patches/0021-Manual-override-of-search-engine-list.patch
This PR replaces default search engine, new tab page and a home page with a stub SERP page.
=> Simple serp

patches/0005-Change-new-tab-page-and-home-page-url.patch
The new Home page is a simple Github Page https://github.com/ghostery/user-agent-desktop/tree/gh-pages
=> New Home Page

patches/0028-Move-Ghostery-icon-to-UrlBar.patch
=> Put Ghostery icon in urlbar of all windows

patches/0005-Change-new-tab-page-and-home-page-url.patch, patches/0021-Manual-override-of-search-engine-list.patch
Replace default search engine with ghosterysearch.com
=> Ghostery Search

.workspace
Add Browser UA detection: https://github.com/ghostery/ghostery-extension/pull/602
Fixes https://github.com/ghostery/user-agents/issues/21
=> Bump ghostery extension to 8.5.3

brands/ghostery/branding/pref/firefox-branding.js, patches/.index, patches/0030-Remove-Lockwise-branding-in-about-logins.patch
=> Remove Firefox branding from about:logins

.workspace
First iteration of search engine choice screen.
Integrates: https://github.com/ghostery/ghostery-search-extension/pull/1
=> Search Engine Choice Onboarding

fern/core/managed-patches.js, fern/patches/hardcoded-strings.js
=> Replace Firefox strings in appstrings.properties

patches/0027-Ghostery-theme.patch
fix #267
Additionally
* move addon badge 2px down - fix #291
* fix Window toolbar text - fix #266
* bump theme version - fix #77 (hopefully)
=> Update Ghostery theme

.workspace
Implemented in https://github.com/ghostery/ghostery-search-extension/pull/5
=> Basic ghosterysearch login flow

ci/build-helpers.groovy
In #301 I forgot that this task runs on windows, so we have to use a windows batch command.
=> Fix artifact deletion on windows worker

patches/.index, patches/0030-Fix-Windows-hidpi-issue.patch
=> Fix windows hidpi issue

brands/ghostery/branding/pref/firefox-branding.js
Blocked until onboarding flow is fixed.
=> Revert cookie settings

.workspace
https://www.mozilla.org/en-US/firefox/82.0.2/releasenotes/
=> Merge Firefox 82.0.2

patches/.index, patches/0032-Add-DNS-and-websocket-permissions-to-ghostery-extens.patch
=> Add permissions to ghostery extension

brands/ghostery/branding/pref/firefox-branding.js
Uses the new endpoint set up here: https://github.com/ghostery/user-agents/pull/35
=> Switch to our own detect portal

.workspace
https://github.com/ghostery/ghostery-search-extension/pull/18
=> Search Extension version bump

brands/ghostery/branding/pref/firefox-branding.js
See also https://github.com/ghostery/user-agents/pull/36
=> Use ghostery shavar endpoint

.workspace
https://github.com/ghostery/ghostery-search-extension/releases/tag/v0.1.12
=> Search extension v0.1.12

.workspace
Changelog:
https://github.com/ghostery/ghostery-search-extension/commit/7b9a3bae1ccd3db69f6358db0a02d89aa09379e9
=> Search Extension Update

patches/.index, patches/0034-Feather-icons.patch, patches/0035-Update-text-on-about-license.patch
=> About license

brands/ghostery/branding/pref/firefox-branding.js
=> Disable Firefox Monitor

patches/.index, patches/0034-Feather-icons.patch, patches/0035-Update-text-on-about-license.patch, patches/0036-Hide-addon-recommendation-badge.patch
=> Hide addon recommendation badge

patches/.index, patches/0034-Feather-icons.patch, patches/0035-Update-text-on-about-license.patch, patches/0036-Hide-addon-recommendation-badge.patch
=> Disable ion / pionner studies

patches/.index, patches/0037-Disable-ion-pioneer-studies.patch
=> Disable ion / pioneer studies

brands/ghostery/mozconfig
=> Enable official builds

ci/submitter.py, ci/uadpy/const.py
* Use our own CDN for all updates
* Push a release notes tab for every build
=> Show release notes on update

brands/ghostery/branding/pref/firefox-branding.js
=> Enabled HTTPs only mode and camera kill switches

brands/ghostery/branding/branding.nsi, build/configs/win64.mozconfig, ci.multibranch.Jenkinsfile, ci/build-helpers.groovy, ci/sign_win.bat, patches/.index, patches/0039-Custom-strings-for-Stub-installer.patch, patches/0040-Remove-Firefox-strings-for-new-install-page.patch
Installer text can be modified in this file: https://searchfox.org/mozilla-central/source/browser/locales/en-US/installer/nsisstrings.properties#21-33
Additional things which we should have before we start using this installer
Fixes #377. Closes #349
=> Windows stub installer

build/configs/win64-aarch64.mozconfig
=> Create stub installer for windows ARM builds

ci.multibranch.Jenkinsfile, ci/build-helpers.groovy, ci/win_signer.bat
This should give us signed mar contents. Fixes #365
=> Windows: sign before packaging

ci.pgo-profile.Jenkinsfile
#387 changed the arguments to the build method. This PR updates the PGO jenkinsfile for this change.
=> Update for changed build arguments

patches/.index, patches/0041-Force-openURL-on-all-updates.patch
Attempting to get pushing urls for updates to work.
=> Force openURL on all updates

.workspace
Use content script to communicate Ghostery account state to ghosterysearch
=> Search extension vesion bump

.gitignore, l10n/.gitignore, patches/0003-Change-new-tab-page-and-home-page-url.patch, patches/0006-Remove-tracking-protection-panel-from-url-bar.patch, patches/0018-Manual-override-of-search-engine-list.patch, patches/0022-Ghostery-theme.patch, patches/0024-Remove-Lockwise-branding-in-about-logins.patch, patches/0031-Feather-icons.patch, patches/0034-Disable-ion-pioneer-studies.patch, patches/0038-Ignore-the-glinter.patch
=> Dark theme by default

brands/ghostery/branding/pref/firefox-branding.js
=> Remove app version from shavar update url.

.workspace
See https://www.mozilla.org/en-US/firefox/84.0.1/releasenotes/
=> Bump Firefox to 84.0.1

ci.multibranch.Jenkinsfile, ci/build-helpers.groovy, ci/sign_mac.sh, ci/unify_mac_dmg.sh
When signing the mac dmg, generate a mar from the signed contents.
=> Create signed mac mar

patches/0022-Ghostery-theme.patch
Changes:
* remove background of unfocused back button 
* remove border of unfocused urlbar
* adds padding to urlbar (so icons don't cover the urlbar border radius)
=> UrlBar Theme tweaks

.workspace
https://github.com/ghostery/ghostery-search-extension/pull/39
https://github.com/ghostery/ghostery-extension/pull/647
=> Search addon version bump

patches/0022-Ghostery-theme.patch
=> Update default theme version

brands/ghostery/branding/branding.nsi, brands/ghostery/branding/configure.sh, brands/ghostery/branding/locales/en-US/brand.dtd, brands/ghostery/branding/locales/en-US/brand.ftl, brands/ghostery/mozconfig, ci/Ghostery-dmg.json
Ghostery Browser from now on will be called Ghostery Dawn
=> Ghostery Dawn

brands/ghostery/mozconfig
=> Revert profile folder location

ci.multibranch.Jenkinsfile
To prevent this problem https://github.com/github-release/github-release/issues/111
=> CD fix: use curl instead of github-release

ci.multibranch.Jenkinsfile, ci.partial-updates.Jenkinsfile
Based on https://stackoverflow.com/a/40216228
=> CD: fix curl upload

brands/ghostery/branding/pref/firefox-branding.js
=> Disable battery status fingerprinting

brands/ghostery/branding/pref/firefox-branding.js
=> Enforce Punycode for IDN to eliminate spoofing

fern/patches/l10n.js, patches/.index, patches/0029-Add-DNS-search-and-websocket-permissions-to-ghostery.patch, patches/0035-Remove-Firefox-strings-for-new-install-page.patch
=> Remove Firefox and Firefox Sync from about:newinstall

CODEOWNERS, README.md, brands/ghostery/branding/pref/Better-Fox.js, patches/.index, patches/0039-Better-Fox-integration.patch
We are welcoming [Better-Fox](https://github.com/yokoffing/Better-Fox) in User Agent Community. Better-Fox from now on will be guiding the User Agent project in making changes to Firefox preferences.
It's great to have you around @yokoffing
=> Better-Fox integration

.workspace
Fixes a telemetry bug on the Create Account view of onboarding
=> Update GBE build to d5dad518

brands/ghostery/branding/pref/Better-Fox.js
Glad to finally contribute to the codebase of this project!
Closes #500
=> Close Window With Last Tab, Fixes #500

ci/sign_mac.sh, fern/core/addons.js, package-lock.json, package.json
appdmg was causing issue on some Linux system and as we only need it on MacOS we can access it via npx
fix #507
=> Remove appdmg from dependencies

brands/ghostery/branding/pref/Better-Fox.js
=> Hide bookmarks toolbar

patches/.index, patches/0039-Default-top-sites.patch
=> Update default top sites

patches/0039-Default-top-sites.patch
=> Default sites icons

patches/0022-Ghostery-theme.patch
=> Default theme update

.workspace
https://github.com/ghostery/ghostery-newtab-extension/pull/12
=> New Tab: WTM Chart

build/Linux.dockerfile, build/MacOSARM.dockerfile, build/MacOSX.dockerfile, build/Windows.dockerfile, build/WindowsARM.dockerfile
This fixes PGO builds for Windows
=> Build tools update

brands/ghostery/branding/content/aboutDialog.css, patches/0004-Update-text-in-about-dialog.patch
=> About dialog links and image fix

.gitignore, ci/build-helpers.groovy
fix #509 
fix #508 
fix GDA-127
fix GDA-129
=> Google API keys for safe browsing ang geo location

.workspace
Release notes: https://www.mozilla.org/en-US/firefox/86.0.1/releasenotes/
=> Firefox 86.0.1

brands/ghostery/branding/pref/Better-Fox.js
- Remove depreciated prefs and prefs now set as the default by Mozilla
- Disable javascript in PDF files
- Block virtual reality by default
=> betterfox: changes for FF87-88

.workspace, brands/ghostery/branding/pref/firefox-branding.js, fern/patches/ghostery-branding.js, l10n/de.json, l10n/en-US.json, l10n/es-ES.json, l10n/fr.json, l10n/hu.json, l10n/it.json, l10n/ja.json, l10n/ko.json, l10n/nl.json, l10n/pl.json, l10n/pt_BR.json, l10n/ru.json, l10n/zh_CN.json, l10n/zh_TW.json, patches/.index, patches/0022-Ghostery-Theme.patch, patches/0039-Ghostery-insights.patch
Changes:
* fixes for Ghostery Private Theme
* Ghost Mode layout fixes
* Ghostery Insights addon integration
* Ghostery Glow browser action
=> 2021.08 release candidate

brands/ghostery/branding/pref/Better-Fox.js
Removing Firefox defaults. Adding a few new prefs.
=> betterfox.js: Prep for Firefox 91

.workspace
=> Extension version bump
