build/configs/ghostery.mozconfig
This PR should enable MAR verification. After merging, automated updates should stop working. Another PR will follow that replace public keys for MAR verification which should reenable the updates.
=> Enable MAR verification

ci/build-helpers.groovy, fern/commands/use.js
This PR fixes the CI which now fails on first build.
Failure happens as `mozconfig` file that has to be added to docker context was only copied with `fern use` - which happens too late.
=> CD: copy mozconfig file before the build starts

brands/ghostery/mozconfig, patches/.index, patches/0011-Force-healthreport-and-normandy-off-at-configure-tim.patch
#201 Remove 'Data Collection and Use' from preferences - Done by totally disabling all telemetry (healthreport, normandy, crash reporter and normal telemetry) at compile time. This unsets the `MOZ_DATA_REPORTING` flag, which means that the [preference section is not included](https://searchfox.org/mozilla-central/source/browser/components/preferences/privacy.inc.xhtml#837).
=> Disable data collection and use preferences section. Fixes #201

ci/sign_mac.sh
The crashreporter app is no longer included in the app bundle since this was disabled in the build in #217
=> Remove crashreporter from mac signing

.gitignore, build/Linux.dockerfile, build/MacOSX.dockerfile, build/Windows.dockerfile, build/configs/linux.mozconfig, build/configs/macosx.mozconfig, build/configs/win64.mozconfig, ci.multibranch.Jenkinsfile, ci/build-helpers.groovy, fern.js, fern/commands/config.js
Fern config aims to support developers and CI in managing mozconfig files. 
It assumes that all builds will be configured with `MOZCONFIG=/<path_to_user-agent-destkop>/mozconfig`. 
Options allow to specify: *brand*, *platform* and optional *local* config. 
Local config is meant to be used in development as it allow to pass custom options and test them agains different brands / platforms without manual copy pasting.
=> Fern config - helps to manage mozconfig files

brands/ghostery/branding/content/aboutDialog.css
Part of #58. Replaces 'Nightly' wordmark, with a Ghostery logo.
=> Fix about page wordmark.

brands/ghostery/branding/pref/firefox-branding.js, patches/.index, patches/0013-Override-UA-for-addons.mozilla.org.patch
Unfortunately to do this via an extension we have to disable protection of `addons.mozilla.org`, meaning that 3rd party extensions could potentially exploit that to tamper with the addons site. I'm not sure how critical an issue this could be.
=> Spoof UA on addons.mozilla.org so that addons can be installed

patches/.index, patches/0028-Move-Ghostery-icon-to-UrlBar.patch
=> Move Ghostery icon into UrlBar

patches/0021-Manual-override-of-search-engine-list.patch
Extension ID was changes and as the list of search engines is hardcoded the ghosterysearch.com was not shown.
=> Fix missing ghostery search

brands/ghostery/branding/configure.sh, brands/ghostery/mozconfig
Fixes a regression since #290 that `MOZ_APP_BASENAME` was set to `Firefox`.
=> Restore Ghostery in UA string.

ci/build-helpers.groovy
Since we bumped version number we are still publishing a 2020.9 windows build to releases. This is because the workdir on the windows signer is not being clean up, so old build artifacts will be resigned and re-archived.
=> Clean up work dir on windows signer

brands/ghostery/branding/pref/firefox-branding.js
Disables the dropdown when there is an empty query. On a new profile this was suggesting 'Search with Google'.
=> Disable dropdown suggestion of topsites and search engines. Fixes #250

fern/patches/hardcoded-strings.js
Just to make sure the Firefox strings are not surfaced in the Ghostery.exe metadata.
=> Update "Firefox" strings in windows manifest.

patches/0024-Ghostery-theme.patch
On top of Firefox 82 themes now update correctly if both manifest and installation call specify correct versions.
fix #266
fix #277
=> Default theme update

brands/ghostery/branding/pref/firefox-branding.js
Reverts ghostery/user-agent-desktop#326
This is causing some issues as the get.ghosterybrowser.com endpoint auto-upgrades http connections and caches this upgrade, so the detect mechanism isn't working properly. We will have to deploy a new endpoint for this, or continue to use firefox's detect portal.
=> Revert "Switch to our own detect portal"

.workspace
Security fix from Mozilla: https://www.mozilla.org/en-US/firefox/82.0.3/releasenotes/
=> Bump Firefox to 82.0.3

.workspace, fern/commands/use.js, fern/core/firefox.js
This adds the IPFS address of a folder of browser resources in the workspace, which serves the following purposes:
* Enables downloading of firefox source via IPFS on CI. This replaces the IPNS link we were using before, as this was slow to update, and is also not immutable like the IPFS address. Therefore using IPFS address is better for keeping older builds reproducable.
* The IPFS folder also contains toolchains needed for building, so anyone wanting to build the project can quickly reference this address to get the full toolchain needed to build the browser.
=> Keep IPFS address of browser resources in workspace

patches/.index, patches/0034-Feather-icons.patch
First batch of replaced icons include:
* menu
* home
* print
* library
* search
* sidebar
Replacing other is possible but he process is not very straightforward as:
1. some Firefox icons like start, left arrow, right arrow look very similar to feather
2. all Feather icons have to be manually edited to make them work in the browser (minor changes in most cases)
3. some icons are not easy to be mapped example Library with I’ve replaced with Open Book
4. some icons include animations like Refresh, they will take time to implement (probably both on design and code side)
=> Feather icons

.workspace
This version removed MyOfferz integration completely and should disable Ghostery  Extension onboarding.
=> Ghostery Extension version bump

patches/0003-Change-new-tab-page-and-home-page-url.patch
Instead of replacing new tab page url from `about:newtab` to something else, we change what `about:newtab` renders.
fix #254
=> Fix blank newtab not working

build/WindowsARM.dockerfile, build/configs/win64-aarch64.mozconfig, build/configs/win64.mozconfig, ci.multibranch.Jenkinsfile, ci.nightly.Jenkinsfile, ci/bootstrap_windows.sh, ci/build-helpers.groovy, ci/uadpy/common.py, fern/commands/build.js, fern/core/docker.js
Note, while I have the aarch64 build for Linux also working, I'm omitting it as there doesn't seem to be a target audience for it. This avoids the extra work needed to support linux ARM builds---they require changes to the base image to get arm libraries, while for the windows builds we don't need that as everything is in the SDK.
=> Windows aarch64 Build

patches/.index, patches/0038-Hide-learn-more-link-on-network-error-pages.patch
Example test page: https://wrong.host.badssl.com/
=> Hide learn more link on network error pages.

ci/sign_win.bat
This failed on nightly as the signing script assumes `x86_64`: http://magrathea.cliqz:8080/blue/organizations/jenkins/user-agent%2Fdesktop/detail/master/197/pipeline/
=> Fix signing of WindowsARM builds

patches/0022-Ghostery-theme.patch
In the previous PR https://github.com/ghostery/user-agent-desktop/pull/413 I've made attempt to change default theme id. This unfortunately didn't. DEFAULT_THEME_ID and its actual value is hardcoded in numerous places. Changing those to new value does not seem to yield good results. As this change appears to be too complicated, this PR reverts previous changes and simply modifies the default theme.
=> Fix default theme

ci/submitter.py
Ensures that ARM macs get the same updates as intel macs.
=> Add Darwin aarch64 platform to release data.

ci/partials.py
This saves us CI time for lang/platform combinations which have few users.
We may want in future to tweak this behaviour for nightly/release builds. i.e. minimal partials for nightly, and all partials for release.
=> Restrict locales and platforms we make partials for

README.md, ci.multibranch.Jenkinsfile, package.json
human-web was a temporal github organization hosting first iteration of user-agent-desktop project and it does not exist anymore.
=> Remove human-web references

brands/ghostery/branding/locales/en-US/brand.dtd, brands/ghostery/branding/locales/en-US/brand.properties
In quite few places the browser is still referencing to itself as to `Ghostery` which may be misleading to some users.
=> Rebranding follow up

patches/0018-Manual-override-of-search-engine-list.patch
This change requires Ghostery Addon update as the identifier of Startpage changes from `StartPage` to `Startpage`
=> Update Startpage branding

.workspace, patches/.index, patches/0001-Include-addons-in-browser-bundle.patch, patches/0003-Change-new-tab-page-and-home-page-url.patch, patches/0005-Remove-bundled-mozilla-extensions.patch, patches/0038-Replace-New-Tab-with-Ghostery-New-Tab-Addon.patch
This PR replaces landing page of Ghostery Glow in a role of New Tab Page with a dedicated addon.
Light theme:
Dark theme:
=> New New Tab Page

.workspace, patches/0029-Add-DNS-search-and-websocket-permissions-to-ghostery.patch
Reverts ghostery/user-agent-desktop#478 as new build is again a firefox one.
fixes:
* Next button on Search Selection screen works again
* Safer handling of unknown search engine names
* Setting Startpage works (again)
=> Ghostery Addon version bump

brands/ghostery/branding/pref/Better-Fox.js
Thank you for inviting me to be apart of the Ghostery team at a community level!
This file will give everyday mainstream users the optimal privacy, security, and annoyance-free settings right out-of-the-box. `BetterFox` was designed to allow users as much privacy as possible up to the point of experiencing breakage.
From the original `BetterFox user.js`, **I have flagged for removal:**
- numerous prefs I've [already added](https://github.com/ghostery/user-agent-desktop/blob/13e51f0da7d2739174f090b756d34a90dbd66f57/brands/ghostery/branding/pref/firefox-branding.js) to the `firefox-branding.js`, which disables Mozilla-specfic products; 
- prefs that Mozilla preconfigures each release by user hardware (e.g., Webrender vs. Webrender Software).
**I also excluded:**
- disabling the pref that …
=> BetterFox 

brands/ghostery/branding/pref/firefox-branding.js
Contents:
1) Enable Ghostery-specific branding prefs
2) Disable Firefox-specific branding prefs
We will use the future BetterFox pref file to harden Ghostery Dawn (e.g., link tracking, cookies, etc.)
=> Limit code to Ghostery updates, search, etc.

brands/ghostery/branding/pref/firefox-branding.js
Related to Lockwise:
```
pref("browser.contentblocking.report.lockwise.enabled", false);
pref("browser.contentblocking.report.lockwise.how_it_works.url", "");
```
***
Remove "Suggest and generate strong passwords". In my testing, this doesn't work without Lockwise.
**Before:**
**After** setting `signon.generation.available` and `signon.generation.enabled` to `false` :
=> Remove Lockwise leftovers + password generation

brands/ghostery/branding/pref/firefox-branding.js
The lack of `devtools.selfxss.count` causes devtools to throw errors instead of logging to console.
Fortunately it looks that's the only one we're missing from original firefox-prefs.js https://github.com/mozilla/gecko-dev/blob/release/browser/branding/official/pref/firefox-branding.js
=> Prefs: bring back mandatory defaults

brands/ghostery/branding/pref/Better-Fox.js
Superseded by privacy.partition.network_state
https://bugzilla.mozilla.org/show_bug.cgi?id=1687618
=> Remove browser.cache.cache_isolation

brands/ghostery/branding/pref/Better-Fox.js
```
// PREF: Disable hiding mime types (Options>General>Applications) not associated with a plugin
user_pref("browser.download.hide_plugins_without_extensions", false); // default=true
```
No longer in Firefox as of v.86.
=> "Disable hiding mime types" depreciated

patches/0022-Ghostery-Theme.patch
It looks like that under some conditions default theme does not update correctly, or it does partially. 
What we observed: 
On introduction of default theme changes so users don't see parts of the theme update. If they change the theme manually, all gets into order, but only until next restart. 
My suspicion is that stylesheet defined in theme's manifest `theme_experiment` section get cached. 
So as a dirty solution we can try to rename that file on each change so there will be no risk of fetching old version from cache.
=> Ghostery Theme caching fix

build/Base.dockerfile
Build was crashing with:
```
importlib_metadata.PackageNotFoundError: No package metadata was found for importlib_metadata
```
Mozilla report: https://bugzilla.mozilla.org/show_bug.cgi?id=1698453
Mozilla fix: https://phabricator.services.mozilla.com/D108485
=> Fix build: pin pip-tools version

brands/ghostery/branding/pref/firefox-branding.js
Depreciated prefs, or now set as the default by Mozilla
=> branding: Updates for FF87-88

ci.multibranch.Jenkinsfile
MacOS updates got broken on nightly as ARM builds were uploaded to github and balrog instead of the x86 (unified/fat) builds.
There was no code change - the problem was always there but was not visible due to `find` command default sorting. If the x86 file was first, all was fine as second file with the same name is silently ignored (during github upload, not sure about balrog).
It may be the `find` version was updated in the docker image we are using which caused the sort order to change and that way was breaking the release pipeline.
=> Fix MacOS updates
